server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE

#    Bootstarpt.yml
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

  zipkin:
    base-url: http://127.0.0.1:9411/